name: ğŸ§¹ Formats

on:
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "CHANGELOG.md"
  push:
    branches: [main, master]
    paths-ignore:
      - "CHANGELOG.md"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4]
        dependency-version: [prefer-lowest, prefer-stable]

    name: ğŸ§¹ PHP ${{ matrix.php }} â€¢ ${{ matrix.os }} â€¢ ${{ matrix.dependency-version }}

    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: pcov

      - name: ğŸ“š Install Aspell
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y aspell aspell-en
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install aspell
          fi

      - name: ğŸ“ Get Composer cache directory
        id: composer-cache
        shell: bash
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: ğŸ’¾ Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-${{ matrix.php }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-${{ matrix.php }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-

      - name: ğŸ§° Install dependencies via Composer
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: ğŸ¨ Coding Style Checks
        run: composer test:lint

      - name: ğŸ” Type Checks
        run: composer test:types

      - name: ğŸ§ª Refactor Checks
        run: composer test:refactor

      - name: âœï¸ Typo Checks
        run: composer test:typos
